### ISSUE TITLE
Help needed with Label Flipping method

### ISSUE THREAD

**Issue by IoanaSil14** [dssg/aequitas#204]
Hi, I am trying out the bias mitigation methods but I keep having the same error when trying to use the Label Flipping method. My code looks like bellow: 

```
from aequitas.flow.methods.preprocessing import label_flipping

y = df.loc[:, target]
X = df.drop(columns=[target], axis=1)
s = X[sensitive_attribute].astype("category")
X = X.drop(columns=[sensitive_attribute], axis=1)

lf = label_flipping.LabelFlipping(
    max_flip_rate=0.1, max_depth=3)
lf.fit(X, y, s)
X_transformed, y_transformed, s_transformed = lf.transform(X, y, s)
```
However I always get the following error triggered from line 345 in label_flipping.py:

![grafik](https://github.com/user-attachments/assets/78d55498-ae2c-4e55-b2af-da73065adc7d)

Can you please give me an indication how to use this method correclty? 
Thank you

**Comment by sgpjesus** [comment]
Hey, It was an error indexing the instances to flip, it was corrected in #206. Thank you for reporting!
