### ISSUE TITLE
Plotting all disparities of a specific model_id when there are multiple models fails

### ISSUE THREAD

**Issue by saleiro** [dssg/aequitas#58]
_assemble_ref_groups needs to create a list of reference groups per model_id otherwise it crashes when we have multiple model_ids in the bias df

**Comment by saleiro** [comment]
I'm not sure if the problem is the _assemble_ref_groups or the fact that the plotting all disparities method does not have a model_id parameter

**Comment by lorenh516** [comment]
Are you using the multimodel branch?

Thank you,

Loren Hinkson
loren.hinkson@gmail.com
310-703-8500
