### ISSUE TITLE
Documentation clarity

### ISSUE THREAD

**Issue by cherdeman** [dssg/aequitas#61]
I'm working through using Aequitas for a bias audit and am noticing a few issues in the documentation:

- The Python API preprocessing input statement is incorrect, it should be `from Aequitas.preprocessing import preprocess_input_df`, i.e. preprocess_input_df should not be callable

- The documentation says that attribute columns can be categorical or continuous, this is confusing in terms of when cleaning functions are called in the pre-processing step. For instance I had made age categories using the cut function that returned a categorical datatype, which caused the discretize cleaning function to be called which then threw an error. It should be clear that categorical columns must be converted to strings.

- Import statements are missing for the Plot and Bias modules; the docs should include `from aequitas.bias import Bias` and `from aequitas.plotting import Plot` in those example calls. 

- The call for the visualization of the disparity treemaps doesn't work as is, it should be `j = p.plot_disparity_all(....` rather than `j = aqp.plot_disparity_all(...` to match the earlier use of Plot().

**Comment by lorenh516** [comment]
Thanks Claire, will begin looking into these items!

**Comment by lorenh516** [comment]
Updates added to doc_clarity_61 branch: https://github.com/dssg/aequitas/tree/doc_clarity_61, looking into 2nd issue opened
